import "@unocss/reset/tailwind.css";

import clsx from "clsx";

import Image from "next/image";
import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import LayoutHeader from "@/components/LayoutHeader";
import LayoutFooter from "@/components/LayoutFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#052e16",
};

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.className,
          "fixed inset-0 flex flex-col bg-black text-white text-[15px] overflow-y-scroll overflow-x-hidden"
        )}
      >
        <Image
          width={1024}
          height={512}
          alt="Strip Background"
          src="/il_strips.png"
          className="absolute inset-x-0 -z-10"
        />
        <div className="flex-1 flex flex-col space-y-32 bg-gradient-to-bl from-black via-green-900/50 to-black l:w-7xl 2xl:self-center overflow-y-scroll overflow-x-hidden">
          <LayoutHeader />
          {children}
          <LayoutFooter />
        </div>
      </body>
    </html>
  );
}
